config/routes.rb
Rails.application.routes.draw do

	namespace :casein do
		resources :pages
		resources :globals
		resources :homepages
	end

  root 'welcome#index'
	get '/help' => 'page#help'
	get '/who' => 'page#who'
	post '/newsletter/signup' => 'page#newsletter'
	get '/mission' => 'page#mission'
	get '/history' => 'page#history'
	get '/board' => 'page#board'
	get '/staff' => 'page#staff'

	get '/partners' => 'page#partners'
	get '/donors' => 'page#donors'
	get '/reports' => 'page#reports'
	get '/donations' => 'page#donations'

	get '/donate' => 'page#donate'
	get '/donations' => 'page#donate'
	get '/celebration' => 'page#celebration'
	get '/donate-equipment' => 'page#equipment'
	get '/assistance' => 'page#assistance'
	get '/donate-vehicle' => 'page#vehicle'

	get '/shop' => 'page#shop'
	get '/volunteer' => 'page#volunteer'

	get '/by-name' => 'page#by_name'
	get '/world-map' => 'page#world_map'

	get '/gallery' => 'page#gallery'

	get '/contact' => 'page#contact'

	get '/recipients' => 'page#recipients'

end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
  
end

app/controllers/casein/globals_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class GlobalsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Globals'
  		@globals = Global.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View global'
      @global = Global.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new global'
    	@global = Global.new
    end

    def create
      @global = Global.new global_params
    
      if @global.save
        flash[:notice] = 'Global created'
        redirect_to casein_globals_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new global'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update global'
      
      @global = Global.find params[:id]
    
      if @global.update_attributes global_params
        flash[:notice] = 'Global has been updated'
        redirect_to casein_globals_path
      else
        flash.now[:warning] = 'There were problems when trying to update this global'
        render :action => :show
      end
    end
 
    def destroy
      @global = Global.find params[:id]

      @global.destroy
      flash[:notice] = 'Global has been deleted'
      redirect_to casein_globals_path
    end
  
    private
      
      def global_params
        params.require(:global).permit(:title, :keyword)
      end

  end
end

app/controllers/casein/homepages_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class HomepagesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Homepages'
  		@homepages = Homepage.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View homepage'
      @homepage = Homepage.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new homepage'
    	@homepage = Homepage.new
    end

    def create
      @homepage = Homepage.new homepage_params
    
      if @homepage.save
        flash[:notice] = 'Homepage created'
        redirect_to casein_homepages_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new homepage'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update homepage'
      
      @homepage = Homepage.find params[:id]
    
      if @homepage.update_attributes homepage_params
        flash[:notice] = 'Homepage has been updated'
        redirect_to casein_homepages_path
      else
        flash.now[:warning] = 'There were problems when trying to update this homepage'
        render :action => :show
      end
    end
 
    def destroy
      @homepage = Homepage.find params[:id]

      @homepage.destroy
      flash[:notice] = 'Homepage has been deleted'
      redirect_to casein_homepages_path
    end
  
    private
      
      def homepage_params
        params.require(:homepage).permit(:title)
      end

  end
end

app/controllers/casein/pages_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class PagesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Pages'
  		@pages = Page.order(sort_order(:header)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View page'
      @page = Page.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new page'
    	@page = Page.new
    end

    def create
      @page = Page.new page_params
    
      if @page.save
        flash[:notice] = 'Page created'
        redirect_to casein_pages_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new page'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update page'
      
      @page = Page.find params[:id]
    
      if @page.update_attributes page_params
        flash[:notice] = 'Page has been updated'
        redirect_to casein_pages_path
      else
        flash.now[:warning] = 'There were problems when trying to update this page'
        render :action => :show
      end
    end
 
    def destroy
      @page = Page.find params[:id]

      @page.destroy
      flash[:notice] = 'Page has been deleted'
      redirect_to casein_pages_path
    end
  
    private
      
      def page_params
        params.require(:page).permit(:header, :content)
      end

  end
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Casein'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for :controller => :casein, :action => :blank
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end
    
  end
end

app/views/casein/homepages/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->


<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :title %>
	</div>
	<div class="col-lg-6">
		
	</div>
</div>

app/views/casein/homepages/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Title", :title %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% homepages.each do |homepage| %>
		<tr>
			<td><%= casein_table_cell_link homepage.title, casein_homepage_path(homepage) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_homepage_path(homepage), :method => :delete, :data => { :confirm => "Are you sure you want to delete this homepage?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/homepages/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Homepages<%= casein_pagination_details @homepages %></h2>

<%= render :partial => 'casein/homepages/table', :locals => { :homepages => @homepages } %>

<div class="text-center">
	<%= will_paginate @homepages %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new homepage".html_safe, new_casein_homepage_path %></li>

<% end %>

app/views/casein/homepages/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Add a new homepage</h2>

<%= form_for @homepage, :url => casein_homepages_path do |f| %>
	
	<%= render :partial => 'casein/homepages/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_homepages_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new homepage", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_homepages_path %></li>
<% end %>

app/views/casein/homepages/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>View homepage</h2>

<%= form_for @homepage, :url => casein_homepage_path(@homepage) do |f| %>

	<%= render :partial => 'casein/homepages/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_homepages_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_homepages_path %></li>
<% end %>